"""Full TA-Lib function catalog — https://ta-lib.org/functions/."""

from __future__ import annotations

# Names match TA-Lib C API (ta_func.h); candlestick patterns prefixed CDL*.
TA_FUNCTION_NAMES: tuple[str, ...] = (
    "AD",
    "ADOSC",
    "ADX",
    "ADXR",
    "APO",
    "AROON",
    "AROONOSC",
    "ATR",
    "AVGPRICE",
    "BBANDS",
    "BETA",
    "BOP",
    "CCI",
    "CDL2CROWS",
    "CDL3BLACKCROWS",
    "CDL3INSIDE",
    "CDL3LINESTRIKE",
    "CDL3STARSINSOUTH",
    "CDL3WHITESOLDIERS",
    "CDLABANDONEDBABY",
    "CDLADVANCEBLOCK",
    "CDLBELTHOLD",
    "CDLBREAKAWAY",
    "CDLCLOSINGMARUBOZU",
    "CDLCONCEALBABYSWALL",
    "CDLCOUNTERATTACK",
    "CDLDARKCLOUDCOVER",
    "CDLDOJI",
    "CDLDOJISTAR",
    "CDLDRAGONFLYDOJI",
    "CDLENGULFING",
    "CDLEVENINGDOJISTAR",
    "CDLEVENINGSTAR",
    "CDLGAPSIDESIDEWHITE",
    "CDLGRAVESTONEDOJI",
    "CDLHAMMER",
    "CDLHANGINGMAN",
    "CDLHARAMI",
    "CDLHARAMICROSS",
    "CDLHIGHWAVE",
    "CDLHIKKAKE",
    "CDLHIKKAKEMOD",
    "CDLHOMINGPIGEON",
    "CDLIDENTICAL3CROWS",
    "CDLINNECK",
    "CDLINVERTEDHAMMER",
    "CDLKICKING",
    "CDLKICKINGBYLENGTH",
    "CDLLADDERBOTTOM",
    "CDLLONGLEGGEDDOJI",
    "CDLLONGLINE",
    "CDLMARUBOZU",
    "CDLMATCHINGLOW",
    "CDLMATHOLD",
    "CDLMORNINGDOJISTAR",
    "CDLMORNINGSTAR",
    "CDLONNECK",
    "CDLPIERCING",
    "CDLRICKSHAWMAN",
    "CDLRISEFALL3METHODS",
    "CDLSEPARATINGLINES",
    "CDLSHOOTINGSTAR",
    "CDLSHORTLINE",
    "CDLSPINNINGTOP",
    "CDLSTALLEDPATTERN",
    "CDLSTICKSANDWICH",
    "CDLTAKURI",
    "CDLTASUKIGAP",
    "CDLTHRUSTING",
    "CDLTRISTAR",
    "CDLUNIQUE3RIVER",
    "CDLUPSIDEGAP2CROWS",
    "CDLXSIDEGAP3METHODS",
    "CMO",
    "CORREL",
    "DEMA",
    "DX",
    "EMA",
    "HT_DCPERIOD",
    "HT_DCPHASE",
    "HT_PHASOR",
    "HT_SINE",
    "HT_TRENDLINE",
    "HT_TRENDMODE",
    "KAMA",
    "LINEARREG",
    "LINEARREG_ANGLE",
    "LINEARREG_INTERCEPT",
    "LINEARREG_SLOPE",
    "MA",
    "MACD",
    "MACDEXT",
    "MACDFIX",
    "MAMA",
    "MAX",
    "MAXINDEX",
    "MEDPRICE",
    "MFI",
    "MIDPOINT",
    "MIDPRICE",
    "MIN",
    "MININDEX",
    "MINMAX",
    "MINMAXINDEX",
    "MINUS_DI",
    "MINUS_DM",
    "MOM",
    "NATR",
    "OBV",
    "PLUS_DI",
    "PLUS_DM",
    "PPO",
    "ROC",
    "ROCP",
    "ROCR",
    "ROCR100",
    "RSI",
    "SAR",
    "SAREXT",
    "SMA",
    "STDDEV",
    "STOCH",
    "STOCHF",
    "STOCHRSI",
    "SUM",
    "T3",
    "TEMA",
    "TRANGE",
    "TRIMA",
    "TRIX",
    "TSF",
    "TYPPRICE",
    "ULTOSC",
    "VAR",
    "WCLPRICE",
    "WILLR",
    "WMA",
)


def ta_function_count() -> int:
    return len(TA_FUNCTION_NAMES)


def all_ta_names() -> tuple[str, ...]:
    from trendalgo.ta.extended_catalog import CUSTOM_TA_NAMES
    from trendalgo.ta.pandas_ta_names_data import PANDAS_TA_FUNCTION_NAMES

    merged = [*TA_FUNCTION_NAMES, *PANDAS_TA_FUNCTION_NAMES, *CUSTOM_TA_NAMES]
    seen: set[str] = set()
    out: list[str] = []
    for name in merged:
        key = name.upper()
        if key in seen:
            continue
        seen.add(key)
        out.append(key)
    return tuple(out)


def all_ta_count() -> int:
    return len(all_ta_names())
