"""Auto-generated glossary for extended TA indicators (pandas-ta-classic)."""

from __future__ import annotations

PANDAS_TA_GLOSSARY_ENTRIES: dict[str, dict[str, str]] = {
    "ABERRATION": {
        "title": "Aberration",
        "short": "A volatility indicator similar to Keltner Channels.",
        "long": "A volatility indicator similar to Keltner Channels. Few internet resources on definitive definition. Request by Github user homily, issue #46 The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Default Inputs: length=5, atr_length=15 ATR = Average True Range SMA = Simple Moving Average ATR = ATR(length=atr_length) JG = TP = HLC3(high, low, close) ZG = SMA(JG, length) SG = ZG + ATR",
    },
    "ABOVE": {
        "title": "Above",
        "short": "Above technical indicator computed from OHLCV bars.",
        "long": "Above is evaluated on each OHLCV bar using open, high, low, close, and volume. Above technical indicator computed from OHLCV bars. Backtests derive entries and exits from the indicator output series.",
        "formula": "ABOVE(open, high, low, close, volume)",
    },
    "ABOVE_VALUE": {
        "title": "Above Value",
        "short": "Above Value technical indicator computed from OHLCV bars.",
        "long": "Above Value is evaluated on each OHLCV bar using open, high, low, close, and volume. Above Value technical indicator computed from OHLCV bars. Backtests derive entries and exits from the indicator output series.",
        "formula": "ABOVE_VALUE(open, high, low, close, volume)",
    },
    "ACCBANDS": {
        "title": "Accbands",
        "short": "Acceleration Bands created by Price Headley plots upper and lower envelope",
        "long": "Acceleration Bands (ACCBANDS) Acceleration Bands created by Price Headley plots upper and lower envelope bands around a simple moving average. The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Default Inputs: length=10, c=4 EMA = Exponential Moving Average SMA = Simple Moving Average HL_RATIO = c * (high - low) / (high + low) LOW = low * (1 - HL_RATIO) HIGH = high * (1 + HL_RATIO) LOWER = EMA(LOW, length)",
    },
    "ACOS": {
        "title": "Acos",
        "short": "Acos technical indicator computed from OHLCV bars.",
        "long": "Vector Trigonometric ACos (TA-Lib: ACOS). The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "ACOS(open, high, low, close, volume)",
    },
    "ADD": {
        "title": "Add",
        "short": "Add technical indicator computed from OHLCV bars.",
        "long": "Element-wise addition of two Series (TA-Lib: ADD). The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "ADD(open, high, low, close, volume)",
    },
    "ALMA": {
        "title": "Alma",
        "short": "The ALMA moving average uses the curve of the Normal (Gauss) distribution, which",
        "long": "Arnaud Legoux Moving Average (ALMA) The ALMA moving average uses the curve of the Normal (Gauss) distribution, which can be shifted from 0 to 1. This allows regulating the smoothness and high The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "refer to provided source",
    },
    "AMAT": {
        "title": "Amat",
        "short": "The Archer Moving Averages Trends indicator identifies trend direction by comparing",
        "long": "Archer Moving Averages Trends (AMAT) The Archer Moving Averages Trends indicator identifies trend direction by comparing fast and slow moving averages. It generates long and short run signals based on the The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": 'Default Inputs: fast=8, slow=21, lookback=2, mamode="ema" FAST_MA = MA(close, fast, mamode) SLOW_MA = MA(close, slow, mamode) AMAT_LR = LONG_RUN(FAST_MA, SLOW_MA, lookback) AMAT_SR = SHORT_RUN(FAST_MA, SLOW_MA, lookback)',
    },
    "AO": {
        "title": "Ao",
        "short": "The Awesome Oscillator is an indicator used to measure a security's momentum.",
        "long": "Awesome Oscillator (AO) The Awesome Oscillator is an indicator used to measure a security's momentum. AO is generally used to affirm trends or to anticipate possible reversals. The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Default Inputs: fast=5, slow=34 SMA = Simple Moving Average median = (high + low) / 2 AO = SMA(median, fast) - SMA(median, slow)",
    },
    "AOBV": {
        "title": "Aobv",
        "short": "Archer On Balance Volume enhances the traditional OBV indicator by applying moving",
        "long": "Archer On Balance Volume (AOBV) Archer On Balance Volume enhances the traditional OBV indicator by applying moving averages and detecting long/short run trends. It provides multiple signals including The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": 'Default Inputs: fast=4, slow=12, max_lookback=2, min_lookback=2, mamode="ema", run_length=2 OBV = On Balance Volume(close, volume) OBV_MIN = ROLLING_MIN(OBV, min_lookback) OBV_MAX = ROLLING_MAX(OBV, max_lookback) FAST_MA = MA(OBV, fast, mamode) SLOW_MA = MA(OBV, slow, mamode) AOBV_LR = LONG_RUN(FAST_MA, SLOW_MA, run_length)',
    },
    "ASIN": {
        "title": "Asin",
        "short": "Asin technical indicator computed from OHLCV bars.",
        "long": "Vector Trigonometric ASin (TA-Lib: ASIN). The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "ASIN(open, high, low, close, volume)",
    },
    "ATAN": {
        "title": "Atan",
        "short": "Atan technical indicator computed from OHLCV bars.",
        "long": "Vector Trigonometric ATan (TA-Lib: ATAN). The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "ATAN(open, high, low, close, volume)",
    },
    "AVOLUME": {
        "title": "Avolume",
        "short": "Population standard deviation of log-returns annualised by sqrt(252).",
        "long": "Annualised Historical Volatility (VOLATILITY) Population standard deviation of log-returns annualised by sqrt(252). Formula: The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Population standard deviation of log-returns annualised by sqrt(252).",
    },
    "BELOW": {
        "title": "Below",
        "short": "Below technical indicator computed from OHLCV bars.",
        "long": "Below is evaluated on each OHLCV bar using open, high, low, close, and volume. Below technical indicator computed from OHLCV bars. Backtests derive entries and exits from the indicator output series.",
        "formula": "BELOW(open, high, low, close, volume)",
    },
    "BELOW_VALUE": {
        "title": "Below Value",
        "short": "Below Value technical indicator computed from OHLCV bars.",
        "long": "Below Value is evaluated on each OHLCV bar using open, high, low, close, and volume. Below Value technical indicator computed from OHLCV bars. Backtests derive entries and exits from the indicator output series.",
        "formula": "BELOW_VALUE(open, high, low, close, volume)",
    },
    "BIAS": {
        "title": "Bias",
        "short": "Rate of change between the source and a moving average.",
        "long": "Bias (BIAS) Rate of change between the source and a moving average. Few internet resources on definitive definition. The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Default Inputs: length=26, MA='sma' BIAS = (close - MA(close, length)) / MA(close, length) = (close / MA(close, length)) - 1",
    },
    "BRAR": {
        "title": "Brar",
        "short": "No internet resources on definitive definition.",
        "long": "BRAR (BRAR) BR and AR No internet resources on definitive definition. The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Default Inputs: length=26, scalar=100 SUM = Sum HO_Diff = high - open OL_Diff = open - low HCY = high - close[-1] CYL = close[-1] - low HCY[HCY < 0] = 0",
    },
    "CE": {
        "title": "Ce",
        "short": "The Chandelier Exit is a volatility-based trailing stop indicator that uses the",
        "long": "Chandelier Exit (CE) The Chandelier Exit is a volatility-based trailing stop indicator that uses the Average True Range (ATR) to determine exit levels. It helps traders stay in a The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Default Inputs: length=22, multiplier=3.0 ATR = Average True Range(length) Highest High = rolling max(high, length) Lowest Low = rolling min(low, length) CE Long = Highest High - (Multiplier * ATR) CE Short = Lowest Low + (Multiplier * ATR)",
    },
    "CEIL": {
        "title": "Ceil",
        "short": "Ceil technical indicator computed from OHLCV bars.",
        "long": "Vector Ceil (TA-Lib: CEIL). The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "CEIL(open, high, low, close, volume)",
    },
    "CFO": {
        "title": "Cfo",
        "short": "The Forecast Oscillator calculates the percentage difference between the actual",
        "long": "Chande Forcast Oscillator (CFO) The Forecast Oscillator calculates the percentage difference between the actual price and the Time Series Forecast (the endpoint of a linear regression line). The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Default Inputs: length=9, drift=1, scalar=100 LINREG = Linear Regression CFO = scalar * (close - LINERREG(length, tdf=True)) / close",
    },
    "CG": {
        "title": "Cg",
        "short": "The Center of Gravity Indicator by John Ehlers attempts to identify turning",
        "long": "Center of Gravity (CG) The Center of Gravity Indicator by John Ehlers attempts to identify turning points while exhibiting zero lag and smoothing. The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Default Inputs: length=10",
    },
    "CHOP": {
        "title": "Chop",
        "short": "The Choppiness Index was created by Australian commodity trader",
        "long": "Choppiness Index (CHOP) The Choppiness Index was created by Australian commodity trader E.W. Dreiss and is designed to determine if the market is choppy The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Default Inputs: length=14, scalar=100, drift=1 HH = high.rolling(length).max() LL = low.rolling(length).min() ATR_SUM = SUM(ATR(drift), length) CHOP = scalar * (LOG10(ATR_SUM) - LOG10(HH - LL)) CHOP /= LOG10(length)",
    },
    "CKSP": {
        "title": "Cksp",
        "short": "The Tushar Chande and Stanley Kroll in their book",
        "long": "Chande Kroll Stop (CKSP) The Tushar Chande and Stanley Kroll in their book “The New Technical Trader”. It is a trend-following indicator, The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Default Inputs: p=10, x=1, q=9, tvmode=True ATR = Average True Range LS0 = high.rolling(p).max() - x * ATR(length=p) LS = LS0.rolling(q).max() SS0 = high.rolling(p).min() + x * ATR(length=p) SS = SS0.rolling(q).min()",
    },
    "CMF": {
        "title": "Cmf",
        "short": "Chailin Money Flow measures the amount of money flow volume over a specific",
        "long": "Chaikin Money Flow (CMF) Chailin Money Flow measures the amount of money flow volume over a specific period in conjunction with Accumulation/Distribution. The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Default Inputs: length=20 ad = close - open ad = 2 * close - high - low hl_range = high - low ad = ad * volume / hl_range CMF = SUM(ad, length) / SUM(volume, length)",
    },
    "COPPOCK": {
        "title": "Coppock",
        "short": 'Coppock Curve (originally called the "Trendex Model") is a momentum indicator',
        "long": 'Coppock Curve (COPC) Coppock Curve (originally called the "Trendex Model") is a momentum indicator is designed for use on a monthly time scale. Although designed for monthly The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.',
        "formula": "Default Inputs: length=10, fast=11, slow=14 SMA = Simple Moving Average MAD = Mean Absolute Deviation tp = typical_price = hlc3 = (high + low + close) / 3 mean_tp = SMA(tp, length) mad_tp = MAD(tp, length) CCI = (tp - mean_tp) / (c * mad_tp)",
    },
    "COS": {
        "title": "Cos",
        "short": "Cos technical indicator computed from OHLCV bars.",
        "long": "Vector Trigonometric Cos (TA-Lib: COS). The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "COS(open, high, low, close, volume)",
    },
    "COSH": {
        "title": "Cosh",
        "short": "Cosh technical indicator computed from OHLCV bars.",
        "long": "Vector Trigonometric Cosh (TA-Lib: COSH). The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "COSH(open, high, low, close, volume)",
    },
    "CPR": {
        "title": "Cpr",
        "short": "Central Pivot Range is a trending indicator that helps identify potential",
        "long": "CPR (Central Pivot Range) Central Pivot Range is a trending indicator that helps identify potential support and resistance levels for the trading session based on previous The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": 'Default Inputs: method="classic", timeframe="daily", levels="standard" Pivot = (H + L + C) / 3 BC = (H + L) / 2 TC = (Pivot - BC) + Pivot R1 = (2 * Pivot) - L S1 = (2 * Pivot) - H R2 = Pivot + (H - L)',
    },
    "CROSS": {
        "title": "Cross",
        "short": "Cross technical indicator computed from OHLCV bars.",
        "long": "Cross is evaluated on each OHLCV bar using open, high, low, close, and volume. Cross technical indicator computed from OHLCV bars. Backtests derive entries and exits from the indicator output series.",
        "formula": "CROSS(open, high, low, close, volume)",
    },
    "CROSSANY": {
        "title": "Crossany",
        "short": "Returns 1 on any bar where series_a and series_b cross (either up or",
        "long": "Cross in either direction (tulipy: CROSSANY). Returns 1 on any bar where series_a and series_b cross (either up or down), 0 otherwise. The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Returns 1 on any bar where series_a and series_b cross (either up or",
    },
    "CROSSOVER": {
        "title": "Crossover",
        "short": "Returns 1 on bars where series_a crosses from below to above series_b,",
        "long": "Crossover: series_a crosses above series_b (tulipy: CROSSOVER). Returns 1 on bars where series_a crosses from below to above series_b, 0 otherwise. Equivalent to cross(series_a, series_b, above=True). The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Returns 1 on bars where series_a crosses from below to above series_b,",
    },
    "CROSS_VALUE": {
        "title": "Cross Value",
        "short": "Cross Value technical indicator computed from OHLCV bars.",
        "long": "Cross Value is evaluated on each OHLCV bar using open, high, low, close, and volume. Cross Value technical indicator computed from OHLCV bars. Backtests derive entries and exits from the indicator output series.",
        "formula": "CROSS_VALUE(open, high, low, close, volume)",
    },
    "CTI": {
        "title": "Cti",
        "short": "The Correlation Trend Indicator is an oscillator created by John Ehler in 2020.",
        "long": "Correlation Trend Indicator (CTI) The Correlation Trend Indicator is an oscillator created by John Ehler in 2020. It assigns a value depending on how close prices in that range are to following The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "The Correlation Trend Indicator is an oscillator created by John Ehler in 2020.",
    },
    "CVI": {
        "title": "Cvi",
        "short": "Chaikins Volatility measures the range between the high and low prices by",
        "long": "Chaikins Volatility (CVI) Chaikins Volatility measures the range between the high and low prices by calculating the rate of change of the exponential moving average of the The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Chaikins Volatility measures the range between the high and low prices by",
    },
    "DECAY": {
        "title": "Decay",
        "short": "Creates a decay moving forward from prior signals like crosses. The default is",
        "long": 'Creates a decay moving forward from prior signals like crosses. The default is "linear". Exponential is optional as "exponential" or "exp". https://tulipindicators.org/decay The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.',
        "formula": 'Default Inputs: length=5, mode=None if mode == "exponential" or mode == "exp":',
    },
    "DECREASING": {
        "title": "Decreasing",
        "short": "Returns True if the series is decreasing over a period, False otherwise.",
        "long": "Returns True if the series is decreasing over a period, False otherwise. If the kwarg 'strict' is True, it returns True if it is continuously decreasing over the period. When using the kwarg 'asint', then it returns 1 for True The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "decreasing = all(i > j for i, j in zip(close[-length:], close[1:])) decreasing = close.diff(length) < 0 decreasing = decreasing.astype(int)",
    },
    "DIV": {
        "title": "Div",
        "short": "Div technical indicator computed from OHLCV bars.",
        "long": "Element-wise division of two Series (TA-Lib: DIV). The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "DIV(open, high, low, close, volume)",
    },
    "DM": {
        "title": "Dm",
        "short": "The Directional Movement was developed by J. Welles Wilder in 1978 attempts to",
        "long": "Directional Movement (DM) The Directional Movement was developed by J. Welles Wilder in 1978 attempts to determine which direction the price of an asset is moving. It compares prior The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": 'Default Inputs: length=14, mamode="rma", drift=1 up = high - high.shift(drift) dn = low.shift(drift) - low pos_ = ((up > dn) & (up > 0)) * up neg_ = ((dn > up) & (dn > 0)) * dn pos_ = pos_.apply(zero) neg_ = neg_.apply(zero)',
    },
    "DONCHIAN": {
        "title": "Donchian",
        "short": "Donchian Channels are used to measure volatility, similar to",
        "long": "Donchian Channels (DC) Donchian Channels are used to measure volatility, similar to Bollinger Bands and Keltner Channels. The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Default Inputs: lower_length=upper_length=20 LOWER = low.rolling(lower_length).min() UPPER = high.rolling(upper_length).max() MID = 0.5 * (LOWER + UPPER)",
    },
    "DPO": {
        "title": "Dpo",
        "short": "Is an indicator designed to remove trend from price and make it easier to",
        "long": "Detrend Price Oscillator (DPO) Is an indicator designed to remove trend from price and make it easier to identify cycles. The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Default Inputs: length=20, centered=True SMA = Simple Moving Average t = int(0.5 * length) + 1 DPO = close.shift(t) - SMA(close, length) DPO = DPO.shift(-t)",
    },
    "DRAWDOWN": {
        "title": "Drawdown",
        "short": "Drawdown is a peak-to-trough decline during a specific period for an investment,",
        "long": "Drawdown (DD) Drawdown is a peak-to-trough decline during a specific period for an investment, trading account, or fund. It is usually quoted as the percentage between the The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "PEAKDD = close.cummax() DD = PEAKDD - close DD% = 1 - (close / PEAKDD) DDlog = log(PEAKDD / close)",
    },
    "DSP": {
        "title": "Dsp",
        "short": "Detrended Synthetic Price removes the trend component from price data to reveal",
        "long": "Detrended Synthetic Price (DSP) Detrended Synthetic Price removes the trend component from price data to reveal the cyclical component. It's useful for cycle analysis and identifying periodic The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Default Inputs: length=14 EMA = EMA(close, length) DSP = close - EMA",
    },
    "EBSW": {
        "title": "Ebsw",
        "short": "This indicator measures market cycles and uses a low pass filter to remove noise.",
        "long": "Even Better SineWave (EBSW) *beta* This indicator measures market cycles and uses a low pass filter to remove noise. Its output is bound signal between -1 and 1 and the maximum length of a detected The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "refer to 'sources' or implementation",
    },
    "EDECAY": {
        "title": "Edecay",
        "short": "Exponential variant of linear decay. At each bar the value decays by",
        "long": "Exponential Decay (EDECAY) Exponential variant of linear decay. At each bar the value decays by exp(-length) from the previous bar, floored at the current close price. The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Exponential variant of linear decay. At each bar the value decays by",
    },
    "EFI": {
        "title": "Efi",
        "short": "Elder's Force Index measures the power behind a price movement using price",
        "long": "Elder's Force Index (EFI) Elder's Force Index measures the power behind a price movement using price and volume as well as potential reversals and price corrections. The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Default Inputs: length=20, drift=1, mamode=None EMA = Exponential Moving Average SMA = Simple Moving Average pv_diff = close.diff(drift) * volume if mamode == 'sma': EFI = SMA(pv_diff, length) EFI = EMA(pv_diff, length)",
    },
    "EMV": {
        "title": "Emv",
        "short": "Raw (unsmoothed) Ease of Movement. Higher values indicate price is moving",
        "long": "Ease of Movement (EMV) Raw (unsmoothed) Ease of Movement. Higher values indicate price is moving up with ease on low volume; lower values indicate the opposite. The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Raw (unsmoothed) Ease of Movement. Higher values indicate price is moving",
    },
    "ENTROPY": {
        "title": "Entropy",
        "short": "Introduced by Claude Shannon in 1948, entropy measures the unpredictability",
        "long": "Entropy (ENTP) Introduced by Claude Shannon in 1948, entropy measures the unpredictability of the data, or equivalently, of its average information. A die has higher The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Default Inputs: length=10, base=2 P = close / SUM(close, length) E = SUM(-P * npLog(P) / npLog(base), length)",
    },
    "EOM": {
        "title": "Eom",
        "short": "Ease of Movement is a volume based oscillator that is designed to measure the",
        "long": "Ease of Movement (EOM) Ease of Movement is a volume based oscillator that is designed to measure the relationship between price and volume flucuating across a zero line. The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Default Inputs: length=14, divisor=100000000, drift=1 SMA = Simple Moving Average hl_range = high - low distance = 0.5 * (high - high.shift(drift) + low - low.shift(drift)) box_ratio = (volume / divisor) / hl_range eom = distance / box_ratio EOM = SMA(eom, length)",
    },
    "ER": {
        "title": "Er",
        "short": 'The Efficiency Ratio was invented by Perry J. Kaufman and presented in his book "New Trading Systems and Methods". It is designed to account for market noise or volatility.',
        "long": 'Efficiency Ratio (ER) The Efficiency Ratio was invented by Perry J. Kaufman and presented in his book "New Trading Systems and Methods". It is designed to account for market noise or volatility. It is calculated by dividing the net change in price movement over N periods by the sum of the absolute net changes over the same N periods. The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.',
        "formula": "Default Inputs: length=10 ABS = Absolute Value EMA = Exponential Moving Average abs_diff = ABS(close.diff(length)) volatility = ABS(close.diff(1)) ER = abs_diff / SUM(volatility, length)",
    },
    "ERI": {
        "title": "Eri",
        "short": "Elder's Bulls Ray Index contains his Bull and Bear Powers. Which are useful ways",
        "long": "Elder Ray Index (ERI) Elder's Bulls Ray Index contains his Bull and Bear Powers. Which are useful ways to look at the price and see the strength behind the market. Bull Power The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Default Inputs: length=13 EMA = Exponential Moving Average BULLPOWER = high - EMA(close, length) BEARPOWER = low - EMA(close, length)",
    },
    "EXP": {
        "title": "Exp",
        "short": "Exp technical indicator computed from OHLCV bars.",
        "long": "Vector Arithmetic Exp (TA-Lib: EXP). The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "EXP(open, high, low, close, volume)",
    },
    "FISHER": {
        "title": "Fisher",
        "short": "Attempts to identify significant price reversals by normalizing prices over a",
        "long": "Fisher Transform (FISHT) Attempts to identify significant price reversals by normalizing prices over a user-specified number of periods. A reversal signal is suggested when the the The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Default Inputs: length=9, signal=1 HL2 = hl2(high, low) HHL2 = HL2.rolling(length).max() LHL2 = HL2.rolling(length).min() HLR = HHL2 - LHL2 HLR[HLR < 0.001] = 0.001 position = ((HL2 - LHL2) / HLR) - 0.5",
    },
    "FLOOR": {
        "title": "Floor",
        "short": "Floor technical indicator computed from OHLCV bars.",
        "long": "Vector Floor (TA-Lib: FLOOR). The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "FLOOR(open, high, low, close, volume)",
    },
    "FOSC": {
        "title": "Fosc",
        "short": "The Forecast Oscillator computes the percentage difference between the actual",
        "long": "Forecast Oscillator (FOSC) The Forecast Oscillator computes the percentage difference between the actual close price and the Time Series Forecast (linear regression projected one step The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "The Forecast Oscillator computes the percentage difference between the actual",
    },
    "FWMA": {
        "title": "Fwma",
        "short": "Fibonacci's Weighted Moving Average is similar to a Weighted Moving Average",
        "long": "Fibonacci's Weighted Moving Average (FWMA) Fibonacci's Weighted Moving Average is similar to a Weighted Moving Average (WMA) where the weights are based on the Fibonacci Sequence. The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Default Inputs: length=10, fibs = utils.fibonacci(length - 1) FWMA = close.rolling(length)_.apply(weights(fibs), raw=True)",
    },
    "HA": {
        "title": "Ha",
        "short": "The Heikin-Ashi technique averages price data to create a Japanese",
        "long": "Heikin Ashi Candles (HA) The Heikin-Ashi technique averages price data to create a Japanese candlestick chart that filters out market noise. Heikin-Ashi charts, The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "HA_OPEN[0] = (open[0] + close[0]) / 2 HA_CLOSE = (open[0] + high[0] + low[0] + close[0]) / 4 HA_OPEN = (HA_OPEN[i−1] + HA_CLOSE[i−1]) / 2 HA_HIGH = MAX(HA_OPEN, HA_HIGH, HA_CLOSE) HA_LOW = MIN(HA_OPEN, HA_LOW, HA_CLOSE)",
    },
    "HILO": {
        "title": "Hilo",
        "short": "The Gann High Low Activator Indicator was created by Robert Krausz in a 1998",
        "long": "Gann HiLo Activator(HiLo) The Gann High Low Activator Indicator was created by Robert Krausz in a 1998 issue of Stocks & Commodities Magazine. It is a moving average based trend The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": 'Default Inputs: high_length=13, low_length=21, mamode="sma" EMA = Exponential Moving Average HMA = Hull Moving Average SMA = Simple Moving Average # Default high_ma = EMA(high, high_length) low_ma = EMA(low, low_length) high_ma = HMA(high, high_length)',
    },
    "HL2": {
        "title": "Hl2",
        "short": "HL2 calculates the median price, which is the average of the High and Low",
        "long": "HL2 (Median Price) HL2 calculates the median price, which is the average of the High and Low prices for each period. This indicator is commonly used to represent the The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Default Inputs: HL2 = (High + Low) / 2",
    },
    "HLC3": {
        "title": "Hlc3",
        "short": "HLC3 calculates the typical price, which is the average of the High, Low,",
        "long": "HLC3 (Typical Price) HLC3 calculates the typical price, which is the average of the High, Low, and Close prices for each period. This indicator provides a simple measure The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Default Inputs: HLC3 = (High + Low + Close) / 3",
    },
    "HMA": {
        "title": "Hma",
        "short": "The Hull Exponential Moving Average attempts to reduce or remove lag in moving",
        "long": "Hull Moving Average (HMA) The Hull Exponential Moving Average attempts to reduce or remove lag in moving averages. The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Default Inputs: length=10 WMA = Weighted Moving Average half_length = int(0.5 * length) sqrt_length = int(sqrt(length)) wmaf = WMA(close, half_length) wmas = WMA(close, length) HMA = WMA(2 * wmaf - wmas, sqrt_length)",
    },
    "HVOL": {
        "title": "Hvol",
        "short": "Historical Volatility is the annualized standard deviation of logarithmic",
        "long": "Historical Volatility (HVOL) Historical Volatility is the annualized standard deviation of logarithmic daily returns over a given period. It measures how much the price has varied The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Historical Volatility is the annualized standard deviation of logarithmic",
    },
    "HWC": {
        "title": "Hwc",
        "short": "Channel indicator HWC (Holt-Winters Channel) based on HWMA - a three-parameter",
        "long": "HWC (Holt-Winter Channel) Channel indicator HWC (Holt-Winters Channel) based on HWMA - a three-parameter moving average calculated by the method of Holt-Winters. The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "HWMA[i] = F[i] + V[i] + 0.5 * A[i] F[i] = (1-na) * (F[i-1] + V[i-1] + 0.5 * A[i-1]) + na * Price[i] V[i] = (1-nb) * (V[i-1] + A[i-1]) + nb * (F[i] - F[i-1]) A[i] = (1-nc) * A[i-1] + nc * (V[i] - V[i-1]) Top = HWMA + Multiplier * StDt Bottom = HWMA - Multiplier * StDt StDt[i] = Sqrt(Var[i-1]) Var[i] = (1-d) * Var[i-1] + nD * (Price[i-1] - HWMA[i-1]) * (Price[i-1] - HWMA[i-1])",
    },
    "HWMA": {
        "title": "Hwma",
        "short": "Indicator HWMA (Holt-Winter Moving Average) is a three-parameter moving average",
        "long": "HWMA (Holt-Winter Moving Average) Indicator HWMA (Holt-Winter Moving Average) is a three-parameter moving average by the Holt-Winter method; the three parameters should be selected to obtain a The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "HWMA[i] = F[i] + V[i] + 0.5 * A[i] F[i] = (1-na) * (F[i-1] + V[i-1] + 0.5 * A[i-1]) + na * Price[i] V[i] = (1-nb) * (V[i-1] + A[i-1]) + nb * (F[i] - F[i-1]) A[i] = (1-nc) * A[i-1] + nc * (V[i] - V[i-1])",
    },
    "ICHIMOKU": {
        "title": "Ichimoku",
        "short": "Developed Pre WWII as a forecasting model for financial markets.",
        "long": "Ichimoku Kinkō Hyō (ichimoku) Developed Pre WWII as a forecasting model for financial markets. https://www.tradingtechnologies.com/help/x-study/technical-indicator-definitions/ichimoku-ich/ The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Default Inputs: tenkan=9, kijun=26, senkou=52 MIDPRICE = Midprice TENKAN_SEN = MIDPRICE(high, low, close, length=tenkan) KIJUN_SEN = MIDPRICE(high, low, close, length=kijun) CHIKOU_SPAN = close.shift(-kijun) SPAN_A = 0.5 * (TENKAN_SEN + KIJUN_SEN) SPAN_A = SPAN_A.shift(kijun)",
    },
    "INCREASING": {
        "title": "Increasing",
        "short": "Returns True if the series is increasing over a period, False otherwise.",
        "long": "Returns True if the series is increasing over a period, False otherwise. If the kwarg 'strict' is True, it returns True if it is continuously increasing over the period. When using the kwarg 'asint', then it returns 1 for True The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "increasing = all(i < j for i, j in zip(close[-length:], close[1:])) increasing = close.diff(length) > 0 increasing = increasing.astype(int)",
    },
    "INERTIA": {
        "title": "Inertia",
        "short": "Inertia was developed by Donald Dorsey and was introduced his article",
        "long": "Inertia (INERTIA) Inertia was developed by Donald Dorsey and was introduced his article in September, 1995. It is the Relative Vigor Index smoothed by the Least The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Default Inputs: length=14, ma_length=20 LSQRMA = Least Squares Moving Average INERTIA = LSQRMA(RVI(length), ma_length)",
    },
    "JMA": {
        "title": "Jma",
        "short": 'Mark Jurik\'s Moving Average (JMA) attempts to eliminate noise to see the "true"',
        "long": 'Jurik Moving Average Average (JMA) Mark Jurik\'s Moving Average (JMA) attempts to eliminate noise to see the "true" underlying activity. It has extremely low lag, is very smooth and is responsive The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.',
        "formula": "Default Inputs: length=7, phase=0",
    },
    "KC": {
        "title": "Kc",
        "short": "A popular volatility indicator similar to Bollinger Bands and",
        "long": "Keltner Channels (KC) A popular volatility indicator similar to Bollinger Bands and Donchian Channels. The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": 'Default Inputs: length=20, scalar=2, mamode=None, tr=True TR = True Range SMA = Simple Moving Average EMA = Exponential Moving Average RANGE = TR(high, low, close) RANGE = high - low if mamode == "ema":',
    },
    "KDJ": {
        "title": "Kdj",
        "short": "The KDJ indicator is actually a derived form of the Slow",
        "long": "KDJ (KDJ) The KDJ indicator is actually a derived form of the Slow Stochastic with the only difference being an extra line The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Default Inputs: length=9, signal=3 LL = low for last 9 periods HH = high for last 9 periods FAST_K = 100 * (close - LL) / (HH - LL) K = RMA(FAST_K, signal) D = RMA(K, signal) J = 3K - 2D",
    },
    "KST": {
        "title": "Kst",
        "short": "The 'Know Sure Thing' is a momentum based oscillator and based on ROC.",
        "long": "'Know Sure Thing' (KST) The 'Know Sure Thing' is a momentum based oscillator and based on ROC. https://www.tradingview.com/wiki/Know_Sure_Thing_(KST) The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Default Inputs: roc1=10, roc2=15, roc3=20, roc4=30, sma1=10, sma2=10, sma3=10, sma4=15, signal=9, drift=1 ROC = Rate of Change SMA = Simple Moving Average rocsma1 = SMA(ROC(close, roc1), sma1) rocsma2 = SMA(ROC(close, roc2), sma2) rocsma3 = SMA(ROC(close, roc3), sma3)",
    },
    "KURTOSIS": {
        "title": "Kurtosis",
        "short": "KURTOSIS = close.rolling(length).kurt()",
        "long": "Rolling Kurtosis length=30 KURTOSIS = close.rolling(length).kurt() The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Default Inputs: length=30 KURTOSIS = close.rolling(length).kurt()",
    },
    "KVO": {
        "title": "Kvo",
        "short": "This indicator was developed by Stephen J. Klinger. It is designed to predict",
        "long": "Klinger Volume Oscillator (KVO) This indicator was developed by Stephen J. Klinger. It is designed to predict price reversals in a market by comparing volume to price. The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Default Inputs: fast=34, slow=55, signal=13, drift=1 EMA = Exponential Moving Average SV = volume * signed_series(HLC3, 1) KVO = EMA(SV, fast) - EMA(SV, slow) Signal = EMA(KVO, signal)",
    },
    "LAG": {
        "title": "Lag",
        "short": "Returns close shifted back by *period* bars. Equivalent to",
        "long": "Lag / Shift (tulipy: LAG). Returns close shifted back by *period* bars. Equivalent to close.shift(period). The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Returns close shifted back by *period* bars. Equivalent to",
    },
    "LINREG": {
        "title": "Linreg",
        "short": "Linear Regression Moving Average (LINREG). This is a simplified version of a",
        "long": "Linear Regression Moving Average (linreg) Linear Regression Moving Average (LINREG). This is a simplified version of a Standard Linear Regression. LINREG is a rolling regression of one variable. A The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Default Inputs: length=14 x = [0, 1, ..., n-1] (matches TA-Lib convention) x_sum = 0.5 * length * (length - 1) x2_sum = length * (length - 1) * (2 * length - 1) / 6 divisor = length * x2_sum - x_sum * x_sum y_sum = series.sum() y2_sum = (series* series).sum()",
    },
    "LINREGANGLE": {
        "title": "Linregangle",
        "short": "Returns the angle (in degrees) of the linear regression line over the",
        "long": "Linear Regression Angle (LINEARREG_ANGLE) Returns the angle (in degrees) of the linear regression line over the last *length* bars. Equivalent to ta.linreg(..., angle=True). The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Returns the angle (in degrees) of the linear regression line over the",
    },
    "LINREGINTERCEPT": {
        "title": "Linregintercept",
        "short": "Returns the y-intercept of the linear regression line over the last",
        "long": "Linear Regression Intercept (LINEARREG_INTERCEPT) Returns the y-intercept of the linear regression line over the last *length* bars. Equivalent to ta.linreg(..., intercept=True). The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Returns the y-intercept of the linear regression line over the last",
    },
    "LINREGSLOPE": {
        "title": "Linregslope",
        "short": "Returns the slope of the linear regression line over the last *length*",
        "long": "Linear Regression Slope (LINEARREG_SLOPE) Returns the slope of the linear regression line over the last *length* bars. Equivalent to ta.linreg(..., slope=True). The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Returns the slope of the linear regression line over the last *length*",
    },
    "LN": {
        "title": "Ln",
        "short": "Ln technical indicator computed from OHLCV bars.",
        "long": "Vector Log Natural (TA-Lib: LN). The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "LN(open, high, low, close, volume)",
    },
    "LOG10": {
        "title": "Log10",
        "short": "Log10 technical indicator computed from OHLCV bars.",
        "long": "Vector Log10 (TA-Lib: LOG10). The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "LOG10(open, high, low, close, volume)",
    },
    "LOG_RETURN": {
        "title": "Log Return",
        "short": "Calculates the logarithmic return of a Series.",
        "long": "Calculates the logarithmic return of a Series. See also: help(df.ta.log_return) for additional **kwargs a valid 'df'. https://stackoverflow.com/questions/31287552/logarithmic-returns-in-pandas-dataframe The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Default Inputs: length=1, cumulative=False LOGRET = log( close.diff(periods=length) ) CUMLOGRET = LOGRET.cumsum() if cumulative",
    },
    "LONG_RUN": {
        "title": "Long Run",
        "short": "Identifies potential long (bullish) trend conditions by detecting when the fast",
        "long": "Identifies potential long (bullish) trend conditions by detecting when the fast moving average is increasing while the slow moving average is either decreasing (potential bottom) or also increasing (confirmed uptrend). The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Default Inputs: length=2 PB = INCREASING(fast, length) AND DECREASING(slow, length) # Potential bottom BI = INCREASING(fast, length) AND INCREASING(slow, length) # Both increasing LONG_RUN = PB OR BI",
    },
    "LRSI": {
        "title": "Lrsi",
        "short": "The Laguerre RSI is a modified RSI indicator that uses Laguerre polynomials to",
        "long": "Laguerre RSI (LRSI) The Laguerre RSI is a modified RSI indicator that uses Laguerre polynomials to reduce lag and provide earlier signals. It adapts to price changes more quickly The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Default Inputs: length=14, gamma=0.5 L0 = (1 - gamma) * Close + gamma * L0[1] L1 = -gamma * L0 + L0[1] + gamma * L1[1] L2 = -gamma * L1 + L1[1] + gamma * L2[1] L3 = -gamma * L2 + L2[1] + gamma * L3[1] CU = sum of (L0-L1, L1-L2, L2-L3) when positive CD = sum of (L0-L1, L1-L2, L2-L3) when negative (absolute)",
    },
    "MAD": {
        "title": "Mad",
        "short": "mad = close.rolling(length).mad()",
        "long": "Rolling Mean Absolute Deviation length=30 mad = close.rolling(length).mad() The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Default Inputs: length=30 mad = close.rolling(length).mad()",
    },
    "MARKETFI": {
        "title": "Marketfi",
        "short": "The Market Facilitation Index (MFI) was developed by Dr. Bill Williams.",
        "long": "Market Facilitation Index (MARKETFI) The Market Facilitation Index (MFI) was developed by Dr. Bill Williams. It measures the efficiency of price movement per unit of volume. A higher The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "The Market Facilitation Index (MFI) was developed by Dr. Bill Williams.",
    },
    "MASSI": {
        "title": "Massi",
        "short": "The Mass Index is a non-directional volatility indicator that utilitizes the",
        "long": "Mass Index (MASSI) The Mass Index is a non-directional volatility indicator that utilitizes the High-Low Range to identify trend reversals based on range expansions. The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Default Inputs: EMA = Exponential Moving Average hl = high - low hl_ema1 = EMA(hl, fast) hl_ema2 = EMA(hl_ema1, fast) hl_ratio = hl_ema1 / hl_ema2 MASSI = SUM(hl_ratio, slow)",
    },
    "MAVP": {
        "title": "Mavp",
        "short": "Moving Average with Variable Period computes a moving average where the",
        "long": "Moving Average with Variable Period (MAVP) Moving Average with Variable Period computes a moving average where the lookback period is different for each bar. The periods Series determines The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Moving Average with Variable Period computes a moving average where the",
    },
    "MCGD": {
        "title": "Mcgd",
        "short": "The McGinley Dynamic looks like a moving average line, yet it is actually a",
        "long": "McGinley Dynamic Indicator The McGinley Dynamic looks like a moving average line, yet it is actually a smoothing mechanism for prices that minimizes price separation, price whipsaws, The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Default Inputs: length=10 offset=0 c=1 denom = (constant * length * (series.iloc[1] / series.iloc[0]) ** 4) series.iloc[1] = (series.iloc[0] + ((series.iloc[1] - series.iloc[0]) / denom)) mcg_cell = close[0:].rolling(2, min_periods=2).apply(mcg_, raw=False) mcg_ds = pd.concat([close[:1], mcg_cell[1:]])",
    },
    "MD": {
        "title": "Md",
        "short": "Rolling mean of absolute deviations from the rolling mean.",
        "long": "Mean Deviation (MD) Rolling mean of absolute deviations from the rolling mean. Equivalent to ta.mad. tulipy name: MD. The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Rolling mean of absolute deviations from the rolling mean.",
    },
    "MEDIAN": {
        "title": "Median",
        "short": "Rolling Median of over 'n' periods. Sibling of a Simple Moving Average.",
        "long": "Rolling Median Rolling Median of over 'n' periods. Sibling of a Simple Moving Average. https://www.incrediblecharts.com/indicators/median_price.php The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Default Inputs: length=30 MEDIAN = close.rolling(length).median()",
    },
    "MMAR": {
        "title": "Mmar",
        "short": "The Madrid Moving Average Ribbon is a visual trend indicator that consists of",
        "long": "Madrid Moving Average Ribbon (MMAR) The Madrid Moving Average Ribbon is a visual trend indicator that consists of multiple EMAs with incrementally increasing periods. It helps identify trend The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Default Inputs: length=10, step=5, num_ribbons=6 period = length + (i * step) MMAR[i] = EMA(close, period)",
    },
    "MSW": {
        "title": "Msw",
        "short": 'Introduced by John F. Ehlers in "Rocket Science For Traders" (2001).',
        "long": 'Mesa Sine Wave (MSW) Introduced by John F. Ehlers in "Rocket Science For Traders" (2001). Uses a DFT of the recent ``period`` bars to estimate phase and outputs The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.',
        "formula": 'Introduced by John F. Ehlers in "Rocket Science For Traders" (2001).',
    },
    "MULT": {
        "title": "Mult",
        "short": "Mult technical indicator computed from OHLCV bars.",
        "long": "Element-wise multiplication of two Series (TA-Lib: MULT). The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "MULT(open, high, low, close, volume)",
    },
    "NPABS": {
        "title": "Npabs",
        "short": "Npabs technical indicator computed from OHLCV bars.",
        "long": "Vector Absolute Value (tulipy: ABS). The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "NPABS(open, high, low, close, volume)",
    },
    "NPROUND": {
        "title": "Npround",
        "short": "Npround technical indicator computed from OHLCV bars.",
        "long": "Vector Round (tulipy: ROUND). The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "NPROUND(open, high, low, close, volume)",
    },
    "NVI": {
        "title": "Nvi",
        "short": "The Negative Volume Index is a cumulative indicator that uses volume change in",
        "long": "Negative Volume Index (NVI) The Negative Volume Index is a cumulative indicator that uses volume change in an attempt to identify where smart money is active. The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Default Inputs: length=1, initial=1000 ROC = Rate of Change roc = ROC(close, length) signed_volume = signed_series(volume, initial=1) nvi = signed_volume[signed_volume < 0].abs() * roc_ nvi.fillna(0, inplace=True) nvi.iloc[0]= initial",
    },
    "OHLC4": {
        "title": "Ohlc4",
        "short": "OHLC4 calculates the average of the Open, High, Low, and Close prices for",
        "long": "OHLC4 (Average of Open, High, Low, Close) OHLC4 calculates the average of the Open, High, Low, and Close prices for each period. This simple average provides a balanced representation of price The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Default Inputs: OHLC4 = (Open + High + Low + Close) / 4",
    },
    "PDIST": {
        "title": "Pdist",
        "short": 'Measures the "distance" covered by price movements.',
        "long": 'Price Distance (PDIST) Measures the "distance" covered by price movements. https://www.prorealcode.com/prorealtime-indicators/pricedistance/ The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.',
        "formula": "Default Inputs: drift=1 PDIST = 2(high - low) - ABS(close - open) + ABS(open - close[drift])",
    },
    "PERCENT_RETURN": {
        "title": "Percent Return",
        "short": "Calculates the percent return of a Series.",
        "long": "Calculates the percent return of a Series. See also: help(df.ta.percent_return) for additional **kwargs a valid 'df'. https://stackoverflow.com/questions/31287552/logarithmic-returns-in-pandas-dataframe The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Default Inputs: length=1, cumulative=False PCTRET = close / close.shift(length) - 1 CUMPCTRET = PCTRET.cumsum() if cumulative",
    },
    "PGO": {
        "title": "Pgo",
        "short": "The Pretty Good Oscillator indicator was created by Mark Johnson to measure the distance of the current close from its N-day Simple Moving Average, expressed in terms of an average true range over a similar period. Johnson's approach was to",
        "long": "Pretty Good Oscillator (PGO) The Pretty Good Oscillator indicator was created by Mark Johnson to measure the distance of the current close from its N-day Simple Moving Average, expressed in terms of an average true range over a similar period. Johnson's approach was to use it as a breakout system for longer term trades. Long if greater than 3.0 and The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Default Inputs: length=14 ATR = Average True Range SMA = Simple Moving Average EMA = Exponential Moving Average PGO = (close - SMA(close, length)) / EMA(ATR(high, low, close, length), length)",
    },
    "PMAX": {
        "title": "Pmax",
        "short": "PMAX is a trend-following indicator that combines moving averages with ATR",
        "long": "PMAX (Price Max) PMAX is a trend-following indicator that combines moving averages with ATR (Average True Range) to create adaptive support and resistance levels. It helps The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Default Inputs: length=10, multiplier=3.0, mamode='ema' ATR = ATR(high, low, close, length) MA = MA(close, length, mamode) PMAX_UP = MA - (multiplier * ATR) PMAX_DOWN = MA + (multiplier * ATR) If close > PMAX_DOWN[1]: trend = 1 (uptrend) If close < PMAX_UP[1]: trend = -1 (downtrend)",
    },
    "PO": {
        "title": "Po",
        "short": "The Projection Oscillator measures the percentage deviation of price from its",
        "long": "Projection Oscillator (PO) The Projection Oscillator measures the percentage deviation of price from its linear regression trend line. It helps identify overbought and oversold conditions The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Default Inputs: length=14 LR = Linear Regression(close, length) PO = 100 * (close - LR) / LR",
    },
    "PSAR": {
        "title": "Psar",
        "short": "Parabolic Stop and Reverse (PSAR) was developed by J. Wells Wilder, that is used",
        "long": "Parabolic Stop and Reverse (psar) Parabolic Stop and Reverse (PSAR) was developed by J. Wells Wilder, that is used to determine trend direction and it's potential reversals in price. PSAR uses a The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Default Inputs: af0=0.02, af=0.02, max_af=0.2",
    },
    "PSL": {
        "title": "Psl",
        "short": "The Psychological Line is an oscillator-type indicator that compares the",
        "long": "Psychological Line (PSL) The Psychological Line is an oscillator-type indicator that compares the number of the rising periods to the total number of periods. In other The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Default Inputs: length=12, scalar=100, drift=1 DIFF = SIGN(close - close[drift]) DIFF = SIGN(close - open) DIFF[DIFF <= 0] = 0 PSL = scalar * SUM(DIFF, length) / length",
    },
    "PVI": {
        "title": "Pvi",
        "short": "The Positive Volume Index is a cumulative indicator that uses volume change in",
        "long": "Positive Volume Index (PVI) The Positive Volume Index is a cumulative indicator that uses volume change in an attempt to identify where smart money is active. The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Default Inputs: length=1, initial=1000 ROC = Rate of Change roc = ROC(close, length) signed_volume = signed_series(volume, initial=1) pvi = signed_volume[signed_volume > 0].abs() * roc_ pvi.fillna(0, inplace=True) pvi.iloc[0]= initial",
    },
    "PVO": {
        "title": "Pvo",
        "short": "Percentage Volume Oscillator is a Momentum Oscillator for Volume.",
        "long": "Percentage Volume Oscillator (PVO) Percentage Volume Oscillator is a Momentum Oscillator for Volume. https://www.fmlabs.com/reference/default.htm?url=PVO.htm The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Default Inputs: fast=12, slow=26, signal=9 EMA = Exponential Moving Average PVO = (EMA(volume, fast) - EMA(volume, slow)) / EMA(volume, slow) Signal = EMA(PVO, signal) Histogram = PVO - Signal",
    },
    "PVOL": {
        "title": "Pvol",
        "short": "Returns a series of the product of price and volume.",
        "long": "Price-Volume (PVOL) Returns a series of the product of price and volume. if signed: The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "pvol = signed_series(close, 1) * close * volume pvol = close * volume",
    },
    "PVR": {
        "title": "Pvr",
        "short": "The Price Volume Rank was developed by Anthony J. Macek and is described in his",
        "long": "Price Volume Rank The Price Volume Rank was developed by Anthony J. Macek and is described in his article in the June, 1994 issue of Technical Analysis of Stocks & Commodities The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "return 1 if 'close change' >= 0 and 'volume change' >= 0 return 2 if 'close change' >= 0 and 'volume change' < 0 return 3 if 'close change' < 0 and 'volume change' >= 0",
    },
    "PVT": {
        "title": "Pvt",
        "short": "The Price-Volume Trend utilizes the Rate of Change with volume to",
        "long": "Price-Volume Trend (PVT) The Price-Volume Trend utilizes the Rate of Change with volume to and it's cumulative values to determine money flow. The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Default Inputs: drift=1 ROC = Rate of Change pv = ROC(close, drift) * volume PVT = pv.cumsum()",
    },
    "PWMA": {
        "title": "Pwma",
        "short": "Pascal's Weighted Moving Average is similar to a symmetric triangular window",
        "long": "Pascal's Weighted Moving Average (PWMA) Pascal's Weighted Moving Average is similar to a symmetric triangular window except PWMA's weights are based on Pascal's Triangle. The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Default Inputs: length=10 triangle = utils.pascals_triangle(length + 1) PWMA = close.rolling(length)_.apply(weights(triangle), raw=True)",
    },
    "QQE": {
        "title": "Qqe",
        "short": "The Quantitative Qualitative Estimation (QQE) is similar to SuperTrend but uses a Smoothed RSI with an upper and lower bands. The band width is a combination of a one period True Range of the Smoothed RSI which is double smoothed using Wilder's smoothing length (2 * rsiLength - 1) and multiplied by the default factor of 4.236. A Long trend is determined when the Smoothed RSI crosses the previous upperband and a Short trend when the Smoothed RSI crosses the previous lowerband.",
        "long": "Quantitative Qualitative Estimation (QQE) The Quantitative Qualitative Estimation (QQE) is similar to SuperTrend but uses a Smoothed RSI with an upper and lower bands. The band width is a combination of a one period True Range of the Smoothed RSI which is double smoothed using Wilder's smoothing length (2 * rsiLength - 1) and multiplied by the default factor of 4.236. A Long trend is determined when the Smoothed RSI crosses the previous upperband and a Short trend when the Smoothed RSI crosses t",
        "formula": 'Default Inputs: length=14, smooth=5, factor=4.236, mamode="ema", drift=1',
    },
    "QSTICK": {
        "title": "Qstick",
        "short": "The Q Stick indicator, developed by Tushar Chande, attempts to quantify and",
        "long": "Q Stick The Q Stick indicator, developed by Tushar Chande, attempts to quantify and identify trends in candlestick charts. The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Default Inputs: length=10 qstick = xMA(close - open, length)",
    },
    "QUANTILE": {
        "title": "Quantile",
        "short": "QUANTILE = close.rolling(length).quantile(q)",
        "long": "Rolling Quantile length=30, q=0.5 QUANTILE = close.rolling(length).quantile(q) The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Default Inputs: length=30, q=0.5 QUANTILE = close.rolling(length).quantile(q)",
    },
    "RAINBOW": {
        "title": "Rainbow",
        "short": "Rainbow Charts use multiple moving averages calculated sequentially, where each",
        "long": "Rainbow Charts Rainbow Charts use multiple moving averages calculated sequentially, where each MA is calculated on the previous MA rather than the price. This creates a The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Default Inputs: length=2, num_ribbons=10 MA1 = SMA(close, length) MA2 = SMA(MA1, length) MA3 = SMA(MA2, length) MA[n] = SMA(MA[n-1], length)",
    },
    "RMA": {
        "title": "Rma",
        "short": "Wilder's Moving Average is simply an Exponential Moving Average (EMA) with",
        "long": "Wilder's Moving Average (RMA) Wilder's Moving Average is simply an Exponential Moving Average (EMA) with a modified alpha = 1 / length. The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Default Inputs: length=10 alpha = 1 / length SMA_nth = SMA(close, length) close[:length - 1] = NaN close[length - 1] = SMA_nth RMA = EWM(close, alpha=alpha, adjust=False)",
    },
    "ROLLING_MAX": {
        "title": "Rolling Max",
        "short": "Rolling Max technical indicator computed from OHLCV bars.",
        "long": "Rolling Maximum over *length* periods (TA-Lib: MAX). The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "ROLLING_MAX(open, high, low, close, volume)",
    },
    "ROLLING_MIN": {
        "title": "Rolling Min",
        "short": "Rolling Min technical indicator computed from OHLCV bars.",
        "long": "Rolling Minimum over *length* periods (TA-Lib: MIN). The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "ROLLING_MIN(open, high, low, close, volume)",
    },
    "ROLLING_SUM": {
        "title": "Rolling Sum",
        "short": "Rolling Sum technical indicator computed from OHLCV bars.",
        "long": "Rolling Summation over *length* periods (TA-Lib: SUM). The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "ROLLING_SUM(open, high, low, close, volume)",
    },
    "RSX": {
        "title": "Rsx",
        "short": "The Relative Strength Xtra is based on the popular RSI indicator and inspired",
        "long": "Relative Strength Xtra (rsx) The Relative Strength Xtra is based on the popular RSI indicator and inspired by the work Jurik Research. The code implemented is based on published code The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Refer to the sources above for information as well as code example.",
    },
    "RVGI": {
        "title": "Rvgi",
        "short": "The Relative Vigor Index attempts to measure the strength of a trend relative to",
        "long": "Relative Vigor Index (RVGI) The Relative Vigor Index attempts to measure the strength of a trend relative to its closing price to its trading range. It is based on the belief that it tends The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Default Inputs: length=14, swma_length=4 SWMA = Symmetrically Weighted Moving Average numerator = SUM(SWMA(close - open, swma_length), length) denominator = SUM(SWMA(high - low, swma_length), length) RVGI = numerator / denominator",
    },
    "RVI": {
        "title": "Rvi",
        "short": "The Relative Volatility Index (RVI) was created in 1993 and revised in 1995.",
        "long": "Relative Volatility Index (RVI) The Relative Volatility Index (RVI) was created in 1993 and revised in 1995. Instead of adding up price changes like RSI based on price direction, the RVI The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Default Inputs: length=14, scalar=100, refined=None, thirds=None EMA = Exponential Moving Average STDEV = Standard Deviation UP = STDEV(src, length) IF src.diff() > 0 ELSE 0 DOWN = STDEV(src, length) IF src.diff() <= 0 ELSE 0 UPSUM = EMA(UP, length) DOWNSUM = EMA(DOWN, length)",
    },
    "SHORT_RUN": {
        "title": "Short Run",
        "short": "Identifies potential short (bearish) trend conditions by detecting when the fast",
        "long": "Identifies potential short (bearish) trend conditions by detecting when the fast moving average is decreasing while the slow moving average is either increasing (potential top) or also decreasing (confirmed downtrend). The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Default Inputs: length=2 PT = DECREASING(fast, length) AND INCREASING(slow, length) # Potential top BD = DECREASING(fast, length) AND DECREASING(slow, length) # Both decreasing SHORT_RUN = PT OR BD",
    },
    "SIN": {
        "title": "Sin",
        "short": "Sin technical indicator computed from OHLCV bars.",
        "long": "Vector Trigonometric Sin (TA-Lib: SIN). The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "SIN(open, high, low, close, volume)",
    },
    "SINH": {
        "title": "Sinh",
        "short": "Sinh technical indicator computed from OHLCV bars.",
        "long": "Vector Trigonometric Sinh (TA-Lib: SINH). The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "SINH(open, high, low, close, volume)",
    },
    "SINWMA": {
        "title": "Sinwma",
        "short": "A weighted average using sine cycles. The middle term(s) of the average have the",
        "long": "Sine Weighted Moving Average (SWMA) A weighted average using sine cycles. The middle term(s) of the average have the highest weight(s). The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Default Inputs: length=10 sines = Series([sin((i + 1) * pi / (length + 1)) for i in range(0, length)]) w = sines / sines.sum() SINWMA = close.rolling(length, min_periods=length).apply(weights(w), raw=True)",
    },
    "SKEW": {
        "title": "Skew",
        "short": "SKEW = close.rolling(length).skew()",
        "long": "Rolling Skew length=30 SKEW = close.rolling(length).skew() The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Default Inputs: length=30 SKEW = close.rolling(length).skew()",
    },
    "SLOPE": {
        "title": "Slope",
        "short": "Returns the slope of a series of length n. Can convert the slope to angle.",
        "long": "Returns the slope of a series of length n. Can convert the slope to angle. Default: slope. length=1 The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Default Inputs: length=1 slope = close.diff(length) / length slope = slope.apply(atan) slope *= 180 / PI",
    },
    "SMC_SWEEP": {
        "title": "Smc Sweep",
        "short": "Identifies when price sweeps below a swing low (or above a swing high),",
        "long": "Smart Money Concept Liquidity Sweep (SMC_SWEEP) Identifies when price sweeps below a swing low (or above a swing high), violently rejects it, leaving a long wick and closing in the opposite direction. The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Default Inputs: length=15, wick_mult=1.5 swing_low = rolling min of low over length bars (shifted 1) swing_high = rolling max of high over length bars (shifted 1) body = abs(close - open) lower_wick = min(open, close) - low upper_wick = high - max(open, close)",
    },
    "SMI": {
        "title": "Smi",
        "short": "The SMI Ergodic Indicator is the same as the True Strength Index (TSI) developed",
        "long": "SMI Ergodic Indicator (SMI) The SMI Ergodic Indicator is the same as the True Strength Index (TSI) developed by William Blau, except the SMI includes a signal line. The SMI uses double The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Default Inputs: fast=5, slow=20, signal=5 TSI = True Strength Index EMA = Exponential Moving Average ERG = TSI(close, fast, slow) Signal = EMA(ERG, signal) OSC = ERG - Signal",
    },
    "SQRT": {
        "title": "Sqrt",
        "short": "Sqrt technical indicator computed from OHLCV bars.",
        "long": "Vector Square Root (TA-Lib: SQRT). The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "SQRT(open, high, low, close, volume)",
    },
    "SQUEEZE": {
        "title": "Squeeze",
        "short": 'The default is based on John Carter\'s "TTM Squeeze" indicator, as discussed',
        "long": 'Squeeze (SQZ) The default is based on John Carter\'s "TTM Squeeze" indicator, as discussed in his book "Mastering the Trade" (chapter 11). The Squeeze indicator attempts The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.',
        "formula": "Default Inputs: bb_length=20, bb_std=2, kc_length=20, kc_scalar=1.5, mom_length=12, mom_smooth=12, tr=True, lazybear=False, BB = Bollinger Bands KC = Keltner Channels MOM = Momentum SMA = Simple Moving Average EMA = Exponential Moving Average",
    },
    "SQUEEZE_PRO": {
        "title": "Squeeze Pro",
        "short": 'This indicator is an extended version of "TTM Squeeze" from John Carter.',
        "long": 'Squeeze PRO(SQZPRO) This indicator is an extended version of "TTM Squeeze" from John Carter. The default is based on John Carter\'s "TTM Squeeze" indicator, as discussed The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.',
        "formula": "Default Inputs: bb_length=20, bb_std=2, kc_length=20, kc_scalar_wide=2, kc_scalar_normal=1.5, kc_scalar_narrow=1, mom_length=12, mom_smooth=6, tr=True, BB = Bollinger Bands KC = Keltner Channels MOM = Momentum SMA = Simple Moving Average",
    },
    "SSF": {
        "title": "Ssf",
        "short": "John F. Ehlers's solution to reduce lag and remove aliasing noise with his",
        "long": "Ehler's Super Smoother Filter (SSF) © 2013 John F. Ehlers's solution to reduce lag and remove aliasing noise with his research in aerospace analog filter design. This indicator comes with two The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Default Inputs: length=10, poles=[2, 3]",
    },
    "STC": {
        "title": "Stc",
        "short": "The Schaff Trend Cycle is an evolution of the popular MACD incorportating two",
        "long": "Schaff Trend Cycle (STC) The Schaff Trend Cycle is an evolution of the popular MACD incorportating two cascaded stochastic calculations with additional smoothing. The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "STCmacd = Moving Average Convergance/Divergance or Oscillator STCstoch = Intermediate Stochastic of MACD/Osc. STC = Schaff Trend Cycle",
    },
    "STDERR": {
        "title": "Stderr",
        "short": "Standard Error is the standard deviation of the sample divided by the square",
        "long": "Standard Error (STDERR) Standard Error is the standard deviation of the sample divided by the square root of the sample size. It estimates the precision of the sample mean as an The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Standard Error is the standard deviation of the sample divided by the square",
    },
    "STDEV": {
        "title": "Stdev",
        "short": "Stdev technical indicator computed from OHLCV bars.",
        "long": "Rolling Standard Deviation length=30 VAR = Variance The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Default Inputs: length=30 VAR = Variance STDEV = variance(close, length).apply(np.sqrt)",
    },
    "SUB": {
        "title": "Sub",
        "short": "Sub technical indicator computed from OHLCV bars.",
        "long": "Element-wise subtraction of two Series (TA-Lib: SUB). The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "SUB(open, high, low, close, volume)",
    },
    "SUPERTREND": {
        "title": "Supertrend",
        "short": "Supertrend is an overlap indicator. It is used to help identify trend",
        "long": "Supertrend (supertrend) Supertrend is an overlap indicator. It is used to help identify trend direction, setting stop loss, identify support and resistance, and/or The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Default Inputs: length=7, multiplier=3.0 MID = multiplier * ATR LOWERBAND = HL2 - MID UPPERBAND = HL2 + MID FINAL_UPPERBAND[i] = UPPERBAND[i] FINAL_UPPERBAND[i] = FINAL_UPPERBAND[i-1]) FINAL_LOWERBAND[i] = LOWERBAND[i]",
    },
    "SWMA": {
        "title": "Swma",
        "short": "Symmetric Weighted Moving Average where weights are based on a symmetric",
        "long": "Symmetric Weighted Moving Average (SWMA) Symmetric Weighted Moving Average where weights are based on a symmetric triangle. For example: n=3 -> [1, 2, 1], n=4 -> [1, 2, 2, 1], etc... The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Default Inputs: length=10 triangle = utils.symmetric_triangle(length - 1) SWMA = close.rolling(length)_.apply(weights(triangle), raw=True)",
    },
    "TAN": {
        "title": "Tan",
        "short": "Tan technical indicator computed from OHLCV bars.",
        "long": "Vector Trigonometric Tan (TA-Lib: TAN). The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "TAN(open, high, low, close, volume)",
    },
    "TANH": {
        "title": "Tanh",
        "short": "Tanh technical indicator computed from OHLCV bars.",
        "long": "Vector Trigonometric Tanh (TA-Lib: TANH). The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "TANH(open, high, low, close, volume)",
    },
    "TD_SEQ": {
        "title": "Td Seq",
        "short": "Tom DeMark's Sequential indicator attempts to identify a price point where an",
        "long": "TD Sequential (TD_SEQ) Tom DeMark's Sequential indicator attempts to identify a price point where an uptrend or a downtrend exhausts itself and reverses. The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Compare current close price with 4 days ago price, up to 13 days. For the consecutive ascending or descending price sequence, display 6th to 9th day value.",
    },
    "THERMO": {
        "title": "Thermo",
        "short": "Elder's Thermometer measures price volatility.",
        "long": "Elders Thermometer (THERMO) Elder's Thermometer measures price volatility. https://www.motivewave.com/studies/elders_thermometer.htm The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Default Inputs: length=20, drift=1, mamode=EMA, long=2, short=0.5 EMA = Exponential Moving Average thermoL = (low.shift(drift) - low).abs() thermoH = (high - high.shift(drift)).abs() thermo = np.where(thermoH > thermoL, thermoH, thermoL) thermo_ma = ema(thermo, length) thermo_long = thermo < (thermo_ma * long)",
    },
    "TODEG": {
        "title": "Todeg",
        "short": "Todeg technical indicator computed from OHLCV bars.",
        "long": "Vector Degrees conversion (tulipy: TODEG). Converts radians to degrees. The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "TODEG(open, high, low, close, volume)",
    },
    "TORAD": {
        "title": "Torad",
        "short": "Torad technical indicator computed from OHLCV bars.",
        "long": "Vector Radians conversion (tulipy: TORAD). Converts degrees to radians. The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "TORAD(open, high, low, close, volume)",
    },
    "TOS_STDEVALL": {
        "title": "Tos Stdevall",
        "short": "A port of TD Ameritrade's Think or Swim Standard Deviation All indicator which",
        "long": "TD Ameritrade's Think or Swim Standard Deviation All (TOS_STDEV) A port of TD Ameritrade's Think or Swim Standard Deviation All indicator which returns the standard deviation of data for the entire plot or for the interval The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Default Inputs: length=None (All), stds=[1, 2, 3], ddof=1 LR = Linear Regression STDEV = Standard Deviation LR = LR(close, length) STDEV = STDEV(close, length, ddof) LOWER = LR - level * STDEV UPPER = LR + level * STDEV",
    },
    "TRIXH": {
        "title": "Trixh",
        "short": "TRIX Histogram extends the TRIX indicator by adding a signal line and histogram.",
        "long": "TRIX Histogram (TRIXH) TRIX Histogram extends the TRIX indicator by adding a signal line and histogram. The histogram represents the difference between TRIX and its signal line, The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Default Inputs: length=18, signal=9, scalar=100 TRIX = TRIX(close, length, scalar) Signal = EMA(TRIX, signal) Histogram = TRIX - Signal",
    },
    "TRUE_RANGE": {
        "title": "True Range",
        "short": "An method to expand a classical range (high minus low) to include",
        "long": "An method to expand a classical range (high minus low) to include possible gap scenarios. https://www.macroption.com/true-range/ The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Default Inputs: drift=1 ABS = Absolute Value prev_close = close.shift(drift) TRUE_RANGE = ABS([high - low, high - prev_close, low - prev_close])",
    },
    "TRUNC": {
        "title": "Trunc",
        "short": "Trunc technical indicator computed from OHLCV bars.",
        "long": "Vector Truncate (tulipy: TRUNC). The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "TRUNC(open, high, low, close, volume)",
    },
    "TSI": {
        "title": "Tsi",
        "short": "The True Strength Index is a momentum indicator used to identify short-term",
        "long": "True Strength Index (TSI) The True Strength Index is a momentum indicator used to identify short-term swings while in the direction of the trend as well as determining overbought The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Default Inputs: fast=13, slow=25, signal=13, scalar=100, drift=1 EMA = Exponential Moving Average diff = close.diff(drift) slow_ema = EMA(diff, slow) fast_slow_ema = EMA(slow_ema, fast) abs_diff_slow_ema = absolute_diff_ema = EMA(ABS(diff), slow) abema = abs_diff_fast_slow_ema = EMA(abs_diff_slow_ema, fast)",
    },
    "TSIGNALS": {
        "title": "Tsignals",
        "short": "Given a Trend, Trend Signals returns the Trend, Trades, Entries and Exits as",
        "long": "Trend Signals Given a Trend, Trend Signals returns the Trend, Trades, Entries and Exits as boolean integers. When 'asbool=True', it returns Trends, Entries and Exits as The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Default Inputs: asbool=False, trend_reset=0, trade_offset=0, drift=1 trades = trends.diff().shift(trade_offset).fillna(0).astype(int) entries = (trades > 0).astype(int) exits = (trades < 0).abs().astype(int)",
    },
    "TTM_TREND": {
        "title": "Ttm Trend",
        "short": "This indicator is from John Carters book “Mastering the Trade” and plots the",
        "long": "TTM Trend (TTM_TRND) This indicator is from John Carters book “Mastering the Trade” and plots the bars green or red. It checks if the price is above or under the average price of The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Default Inputs: length=6 averageprice = (((high[5]+low[5])/2)+((high[4]+low[4])/2)+((high[3]+low[3])/2)+((high[2]+low[2])/2)+((high[1]+low[1])/2)+((high[6]+low[6])/2)) / 6",
    },
    "UI": {
        "title": "Ui",
        "short": "The Ulcer Index by Peter Martin measures the downside volatility with the use of",
        "long": "Ulcer Index (UI) The Ulcer Index by Peter Martin measures the downside volatility with the use of the Quadratic Mean, which has the effect of emphasising large drawdowns. The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Default Inputs: length=14, scalar=100 HC = Highest Close SMA = Simple Moving Average HCN = HC(close, length) DOWNSIDE = scalar * (close - HCN) / HCN UI = SQRT(SMA(DOWNSIDE^2, length) / length) UI = SQRT(SUM(DOWNSIDE^2, length) / length)",
    },
    "UO": {
        "title": "Uo",
        "short": "The Ultimate Oscillator is a momentum indicator over three different",
        "long": "Ultimate Oscillator (UO) The Ultimate Oscillator is a momentum indicator over three different periods. It attempts to correct false divergence trading signals. The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Default Inputs: fast=7, medium=14, slow=28, fast_w=4.0, medium_w=2.0, slow_w=1.0, drift=1 min_low_or_pc = close.shift(drift).combine(low, min) max_high_or_pc = close.shift(drift).combine(high, max) bp = buying pressure = close - min_low_or_pc tr = true range = max_high_or_pc - min_low_or_pc fast_avg = SUM(bp, fast) / SUM(tr, fast)",
    },
    "VARIANCE": {
        "title": "Variance",
        "short": "VARIANCE = close.rolling(length).var()",
        "long": "Rolling Variance length=30 VARIANCE = close.rolling(length).var() The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Default Inputs: length=30 VARIANCE = close.rolling(length).var()",
    },
    "VFI": {
        "title": "Vfi",
        "short": "The Volume Flow Indicator (VFI) is a volume-based indicator that helps identify",
        "long": "Volume Flow Indicator (VFI) The Volume Flow Indicator (VFI) is a volume-based indicator that helps identify the strength of bulls vs bears in the market. It combines price movement with The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Default Inputs: length=130, coef=0.2, vcoef=2.5, mamode='ema' typical = close inter = typical - typical.shift(1) # Price change cutoff = coef * close # Volatility threshold mf = inter if abs(inter) > cutoff else 0 # Filter minimal price changes vave = SMA(volume, length).shift(1) vmax = vave * vcoef",
    },
    "VHF": {
        "title": "Vhf",
        "short": "VHF was created by Adam White to identify trending and ranging markets.",
        "long": "Vertical Horizontal Filter (VHF) VHF was created by Adam White to identify trending and ranging markets. https://www.incrediblecharts.com/indicators/vertical_horizontal_filter.php The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Default Inputs: length = 28 HCP = Highest Close Price in Period LCP = Lowest Close Price in Period Change = abs(Ct - Ct-1) VHF = (HCP - LCP) / RollingSum[length] of Change",
    },
    "VIDYA": {
        "title": "Vidya",
        "short": "Variable Index Dynamic Average (VIDYA) was developed by Tushar Chande. It is",
        "long": "Variable Index Dynamic Average (VIDYA) Variable Index Dynamic Average (VIDYA) was developed by Tushar Chande. It is similar to an Exponential Moving Average but it has a dynamically adjusted The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Default Inputs: length=10, adjust=False, sma=True sma_nth = close[0:length].sum() / length close[:length - 1] = np.NaN close.iloc[length - 1] = sma_nth EMA = close.ewm(span=length, adjust=adjust).mean()",
    },
    "VORTEX": {
        "title": "Vortex",
        "short": "Two oscillators that capture positive and negative trend movement.",
        "long": "Two oscillators that capture positive and negative trend movement. https://stockcharts.com/school/doku.php?id=chart_school:technical_indicators:vortex_indicator length=14, drift=1 The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Default Inputs: length=14, drift=1 TR = True Range SMA = Simple Moving Average tr = TR(high, low, close) tr_sum = tr.rolling(length).sum() vmp = (high - low.shift(drift)).abs() vmn = (low - high.shift(drift)).abs()",
    },
    "VOSC": {
        "title": "Vosc",
        "short": "The Volume Oscillator measures the difference between two volume moving",
        "long": "Volume Oscillator (VOSC) The Volume Oscillator measures the difference between two volume moving averages (fast and slow SMAs) as a percentage of the slow SMA. The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "The Volume Oscillator measures the difference between two volume moving",
    },
    "VP": {
        "title": "Vp",
        "short": "Calculates the Volume Profile by slicing price into ranges.",
        "long": "Volume Profile (VP) Calculates the Volume Profile by slicing price into ranges. Note: Value Area is not calculated. The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Default Inputs: width=10 vp = pd.concat([close, pos_volume, neg_volume], axis=1) vp_ranges = cut(vp[close_col], width) result = ({range_left, mean_close, range_right, pos_volume, neg_volume} foreach range in vp_ranges vp_ranges = np.array_split(vp, width) result = ({low_close, mean_close, high_close, pos_volume, neg_volume} foreach range in vp_ranges vpdf = pd.DataFrame(result)",
    },
    "VWAP": {
        "title": "Vwap",
        "short": "The Volume Weighted Average Price that measures the average typical price",
        "long": "Volume Weighted Average Price (VWAP) The Volume Weighted Average Price that measures the average typical price by volume. It is typically used with intraday charts to identify general The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "tp = typical_price = hlc3(high, low, close) tpv = tp * volume VWAP = tpv.cumsum() / volume.cumsum()",
    },
    "VWMA": {
        "title": "Vwma",
        "short": "Volume Weighted Moving Average.",
        "long": "Volume Weighted Moving Average (VWMA) Volume Weighted Moving Average. https://www.motivewave.com/studies/volume_weighted_moving_average.htm The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Default Inputs: length=10 SMA = Simple Moving Average pv = close * volume VWMA = SMA(pv, length) / SMA(volume, length)",
    },
    "VWMACD": {
        "title": "Vwmacd",
        "short": "Volume Weighted MACD is a variation of the traditional MACD that incorporates",
        "long": "Volume Weighted MACD (VWMACD) Volume Weighted MACD is a variation of the traditional MACD that incorporates volume into the calculation. It uses Volume Weighted Moving Averages (VWMA) The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Default Inputs: fast=12, slow=26, signal=9 FastVWMA = VWMA(close, volume, fast) SlowVWMA = VWMA(close, volume, slow) VWMACD = FastVWMA - SlowVWMA Signal = VWMA(VWMACD, volume, signal) Histogram = VWMACD - Signal",
    },
    "WAD": {
        "title": "Wad",
        "short": "Williams' Accumulation/Distribution line measures the cumulative flow of",
        "long": "Williams Accumulation/Distribution (WAD) Williams' Accumulation/Distribution line measures the cumulative flow of money into and out of a security. Unlike the standard A/D line, it uses The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Williams' Accumulation/Distribution line measures the cumulative flow of",
    },
    "WCP": {
        "title": "Wcp",
        "short": "Weighted Closing Price is the weighted price given: high, low",
        "long": "Weighted Closing Price (WCP) Weighted Closing Price is the weighted price given: high, low and double the close. The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "WCP = (2 * close + high + low) / 4",
    },
    "XSIGNALS": {
        "title": "Xsignals",
        "short": "Cross Signals returns Trend Signal (TSIGNALS) results for Signal Crossings. This",
        "long": "Cross Signals (XSIGNALS) Cross Signals returns Trend Signal (TSIGNALS) results for Signal Crossings. This is useful for indicators like RSI, ZSCORE, et al where one wants trade Entries The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Default Inputs: asbool=False, trend_reset=0, trade_offset=0, drift=1 trades = trends.diff().shift(trade_offset).fillna(0).astype(int) entries = (trades > 0).astype(int) exits = (trades < 0).abs().astype(int)",
    },
    "ZLMA": {
        "title": "Zlma",
        "short": "The Zero Lag Moving Average attempts to eliminate the lag associated",
        "long": "Zero Lag Moving Average (ZLMA) The Zero Lag Moving Average attempts to eliminate the lag associated with moving averages. This is an adaption created by John Ehler and Ric Way. The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Default Inputs: length=10, mamode=EMA EMA = Exponential Moving Average lag = int(0.5 * (length - 1)) SOURCE = 2 * close - close.shift(lag) ZLMA = MA(kind=mamode, SOURCE, length)",
    },
    "ZSCORE": {
        "title": "Zscore",
        "short": "SMA = Simple Moving Average",
        "long": "Rolling Z Score length=30, std=1 SMA = Simple Moving Average The indicator uses standard OHLCV inputs and integrates with the unified TA backtest engine.",
        "formula": "Default Inputs: length=30, std=1 SMA = Simple Moving Average STDEV = Standard Deviation std = std * STDEV(close, length) mean = SMA(close, length) ZSCORE = (close - mean) / std",
    },
}
